# Generated by Django 5.1.5 on 2025-01-30 01:52

import apps.core.models
import django.db.models.deletion
import django.db.models.functions.datetime
import django_editorjs2.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(max_length=200)),
                ("url_name", models.SlugField(max_length=200)),
                ("year", models.PositiveSmallIntegerField()),
                ("text_top", django_editorjs2.fields.EditorJSField(null=True)),
                ("text_bottom_left", django_editorjs2.fields.EditorJSField(null=True)),
                ("text_bottom_right", django_editorjs2.fields.EditorJSField(null=True)),
                ("is_hidden", models.BooleanField(default=False)),
                ("cover", models.ImageField(upload_to=apps.core.models.Project._upload_to_path)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "db_table": "projects",
                "ordering": ("position",),
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("site_description", models.TextField()),
                ("site_keywords", models.TextField()),
                ("intro_image", models.ImageField(upload_to=apps.core.models.SiteSetting._upload_to_path)),
                ("info_left", django_editorjs2.fields.EditorJSField()),
                ("info_right", django_editorjs2.fields.EditorJSField()),
                ("is_active", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
                "db_table": "site_settings",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ProjectImageRow",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="image_rows", to="core.project"
                    ),
                ),
            ],
            options={
                "verbose_name": "Project image row",
                "verbose_name_plural": "Project image rows",
                "db_table": "project_image_rows",
                "ordering": ("position",),
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.ImageField(upload_to=apps.core.models.ProjectImage._upload_to_path)),
                ("mime", models.CharField(max_length=100)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="core.projectimagerow"
                    ),
                ),
            ],
            options={
                "verbose_name": "Project image",
                "verbose_name_plural": "Project images",
                "db_table": "project_images",
                "ordering": ("position",),
                "default_permissions": (),
            },
        ),
    ]
